#!/bin/bash
# ============================================================================
# CBI-V15 MotherDuck Token Setup Script
# ============================================================================
# This script helps you set up MotherDuck tokens from Vercel storage.
# It will:
#   1. Prompt for tokens (from Vercel dashboard)
#   2. Add them to .env file (project root)
#   3. Add them to shell config (~/.bashrc or ~/.zshrc)
#   4. Test the connection
#
# Usage:
#   bash scripts/setup_motherduck_tokens.sh
#
# Token Sources (Vercel):
#   - motherduck_storage_MOTHERDUCK_TOKEN (bottom one - read/write)
#   - motherduck_storage_MOTHERDUCK_READ_SCALING_TOKEN (top one - read-only)
# ============================================================================

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"

echo "============================================================================"
echo "🔐 CBI-V15 MOTHERDUCK TOKEN SETUP"
echo "============================================================================"
echo ""
echo "This script will help you configure MotherDuck tokens."
echo "You'll need tokens from Vercel Dashboard → Settings → Environment Variables"
echo ""

# 1. Capture the Standard Token (The bottom one: motherduck_storage_MOTHERDUCK_TOKEN)
echo "👇 STEP 1: PASTE the 'motherduck_storage_MOTHERDUCK_TOKEN' (Bottom one) and hit Enter:"
read -r INPUT_MAIN_TOKEN

if [ -z "$INPUT_MAIN_TOKEN" ]; then
    echo "❌ ERROR: Main token cannot be empty"
    exit 1
fi

# 2. Capture the Read Scaling Token (The top one: motherduck_storage_MOTHERDUCK_READ_SCALING_TOKEN)
echo ""
echo "👇 STEP 2: PASTE the 'motherduck_storage_MOTHERDUCK_READ_SCALING_TOKEN' (Top one) and hit Enter:"
echo "   (Press Enter to skip if you don't have this token)"
read -r INPUT_SCALE_TOKEN

# 3. Get database name (optional)
echo ""
echo "👇 STEP 3: Enter database name (default: cbi_v15, press Enter to use default):"
read -r INPUT_DB_NAME
INPUT_DB_NAME=${INPUT_DB_NAME:-cbi_v15}

# 4. Update .env file
echo ""
echo "📝 Updating .env file: $ENV_FILE"

# Remove old MotherDuck entries if they exist
if [ -f "$ENV_FILE" ]; then
    # Create backup
    cp "$ENV_FILE" "$ENV_FILE.bak" 2>/dev/null || true
    
    # Remove old entries (using sed compatible with macOS)
    sed -i.bak2 '/^MOTHERDUCK_TOKEN=/d' "$ENV_FILE" 2>/dev/null || true
    sed -i.bak2 '/^MOTHERDUCK_READ_SCALING_TOKEN=/d' "$ENV_FILE" 2>/dev/null || true
    sed -i.bak2 '/^MOTHERDUCK_DB=/d' "$ENV_FILE" 2>/dev/null || true
    sed -i.bak2 '/^motherduck_storage_MOTHERDUCK_TOKEN=/d' "$ENV_FILE" 2>/dev/null || true
    sed -i.bak2 '/^motherduck_storage_MOTHERDUCK_READ_SCALING_TOKEN=/d' "$ENV_FILE" 2>/dev/null || true
    sed -i.bak2 '/^# --- CBI_V15 MOTHERDUCK KEYS ---/d' "$ENV_FILE" 2>/dev/null || true
fi

# Append new entries
echo "" >> "$ENV_FILE"
echo "# --- CBI_V15 MOTHERDUCK KEYS (Auto-generated by setup_motherduck_tokens.sh) ---" >> "$ENV_FILE"
echo "MOTHERDUCK_TOKEN='$INPUT_MAIN_TOKEN'" >> "$ENV_FILE"
if [ -n "$INPUT_SCALE_TOKEN" ]; then
    echo "MOTHERDUCK_READ_SCALING_TOKEN='$INPUT_SCALE_TOKEN'" >> "$ENV_FILE"
fi
echo "MOTHERDUCK_DB='$INPUT_DB_NAME'" >> "$ENV_FILE"
echo "✅ Updated .env file"

# 5. Update shell config
TARGET_FILE=""
if [ -n "$ZSH_VERSION" ]; then
    TARGET_FILE="$HOME/.zshrc"
elif [ -n "$BASH_VERSION" ]; then
    TARGET_FILE="$HOME/.bashrc"
else
    echo "⚠️  Unknown shell. Tokens added to .env only."
    TARGET_FILE=""
fi

if [ -n "$TARGET_FILE" ]; then
    echo ""
    echo "📝 Updating shell config: $TARGET_FILE"
    
    # Remove old entries
    if [ -f "$TARGET_FILE" ]; then
        sed -i.bak '/^# --- CBI_V15 MOTHERDUCK KEYS ---/,/^export MOTHERDUCK_READ_SCALING_TOKEN=/d' "$TARGET_FILE" 2>/dev/null || true
        sed -i.bak '/^export MOTHERDUCK_TOKEN=/d' "$TARGET_FILE" 2>/dev/null || true
        sed -i.bak '/^export MOTHERDUCK_READ_SCALING_TOKEN=/d' "$TARGET_FILE" 2>/dev/null || true
        sed -i.bak '/^export MOTHERDUCK_DB=/d' "$TARGET_FILE" 2>/dev/null || true
    fi
    
    # Append new entries
    echo "" >> "$TARGET_FILE"
    echo "# --- CBI_V15 MOTHERDUCK KEYS (Auto-generated by setup_motherduck_tokens.sh) ---" >> "$TARGET_FILE"
    echo "export MOTHERDUCK_TOKEN='$INPUT_MAIN_TOKEN'" >> "$TARGET_FILE"
    if [ -n "$INPUT_SCALE_TOKEN" ]; then
        echo "export MOTHERDUCK_READ_SCALING_TOKEN='$INPUT_SCALE_TOKEN'" >> "$TARGET_FILE"
    fi
    echo "export MOTHERDUCK_DB='$INPUT_DB_NAME'" >> "$TARGET_FILE"
    
    echo "✅ Updated shell config"
    echo "   Note: Run 'source $TARGET_FILE' or open a new terminal to use tokens"
fi

# 6. Export for current session
export MOTHERDUCK_TOKEN="$INPUT_MAIN_TOKEN"
if [ -n "$INPUT_SCALE_TOKEN" ]; then
    export MOTHERDUCK_READ_SCALING_TOKEN="$INPUT_SCALE_TOKEN"
fi
export MOTHERDUCK_DB="$INPUT_DB_NAME"

# 7. Final Connection Test
echo ""
echo "============================================================================"
echo "🔌 Testing Connection..."
echo "============================================================================"

if python3 -c "
import duckdb
import os
token = os.getenv('MOTHERDUCK_TOKEN')
db = os.getenv('MOTHERDUCK_DB', 'cbi_v15')
con = duckdb.connect(f'md:{db}?motherduck_token={token}')
result = con.execute('PRAGMA database_list;').fetchall()
print('✅ SUCCESS! Connected to:', result)
con.close()
" 2>/dev/null; then
    echo ""
    echo "✅ Connection test passed!"
    echo ""
    echo "============================================================================"
    echo "🎉 SETUP COMPLETE"
    echo "============================================================================"
    echo ""
    echo "Tokens have been configured in:"
    echo "  ✅ .env file: $ENV_FILE"
    if [ -n "$TARGET_FILE" ]; then
        echo "  ✅ Shell config: $TARGET_FILE"
    fi
    echo ""
    echo "Next steps:"
    echo "  1. Verify setup: python scripts/setup/verify_motherduck_tokens.py"
    echo "  2. Test connection: python scripts/test_motherduck_connection.py"
    echo "  3. Read docs: docs/ops/MOTHERDUCK_SETUP.md"
    echo ""
else
    echo ""
    echo "❌ Connection test failed!"
    echo ""
    echo "Troubleshooting:"
    echo "  1. Verify tokens are correct (check Vercel dashboard)"
    echo "  2. Check network connectivity"
    echo "  3. Run: python scripts/setup/verify_motherduck_tokens.py"
    echo "  4. See: docs/ops/MOTHERDUCK_SETUP.md"
    echo ""
    exit 1
fi
